<h1>Nowości</h1>

<div class="swiper-main">
    <div class="swiper-container">
    <!-- Additional required wrapper -->
        <div class="swiper-wrapper">
        <!-- Slides -->
            <?php
                $productCollection = $block->getProductCollection();
                foreach ($productCollection as $product){
                    
                    echo '<div class="swiper-slide">
                            <div class="swiper-slide-content">
                                <div class="stars">
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star checked"></span>
                                    <span class="fa fa-star"></span>
                                    <span class="fa fa-star"></span>
                                </div>
                                <a href= '.$product["productUrl"].' target="_blank">
                                
                                    <img title='.$product["productName"].' src='. $product["productImageUrl"].' />
                                    <span class="PrductName"> '.$product["productName"].' </span>
                                    <p>'.$product["productPrice"].'  zł</p>
                                </a>
                            </div>
                         </div>';
                }
            ?>
    
        </div>
            <!-- If we need pagination -->
        <div class="swiper-pagination"></div>
        <!-- Add Navigation -->
        <div class="swiper-button-prev swiper-button"></div>
        <div class="swiper-button-next swiper-button"></div>
    </div>
</div>

<script>
     require([
        'swiper'
    ], function(Swiper){
                // my code
                var swiper = new Swiper('.swiper-container', {
                // Optional parameters
                    slidesPerView: 4,
                    slidesPerGroup: 4,
                    spaceBetween: 60,
                    loop: true,

                    pagination: {
                    el: ".swiper-pagination",
                    clickable: true,
                    
                    }, 
                    navigation: {
                        nextEl: '.swiper-button-next',
                        prevEl: '.swiper-button-prev',
                    },
                    mousewheel: true,
                    keyboard: true,
                    breakpoints: {
                        1024: {
                            slidesPerView: 4,
                            spaceBetween: 60,
                        },
                        768: {
                            slidesPerView: 3,
                            slidesPerGroup: 3,
                            spaceBetween: 60,
                        },
                        360: {
                            slidesPerView: 2,
                            slidesPerGroup: 2,
                            spaceBetween: 46,
                        }
                    }
                });
            });
</script>

<!--    Rating, Image, Name, Price, Product  -->