<div class="Raki">
    <div class="wrapper">
        <div class="twocolumnsection">
            <div class="firstcolumn">
                <div class="TextBoxTop">
                    <h2>Nowe rozwiązania, dopracowane<br> w najmniejszym detalu</h2>
                    <span class="P1"><strong>Nuptse EVO</strong> to raki wykonane z najlepszej jakości hartowanej stali zapewniającej odpowiednią wytrzymałość i sztywność. 12 długich zębów opartych na ramowej konstrukcji zapewnia świetną przyczepność w lodzie oraz twardym i zmrożonym śniegu. </span>
                </div>
                <div class="BigImage">
                    <img src='<?php echo $this->getViewFileUrl("images/5f8819d029e0de9754892bb6_nuptse-evo-bottom-min.jpg"); ?>' alt="Demo"/>
                </div>
                <div class="TextBoxMiddle"> 
                    <h3>Podkładki przeciwśnieżne</h3>
                    <span class="P1">Climbing Technology zastosowało w nowej wersji Nuptse zupełnie nowe podkładki przeciwśnieżne. Użyty materiał jest bardzo odporny na mróz - nawet w bardzo niskich temperaturach zachowuje elastyczność dzięki czemu podkładki nie niszczą się i nie pękają. Dodatkowo sprężyste wytłoczenie jeszcze lepiej „odbija” śnieg zapewniając bezpieczeństwo.</span>
                </div>
            </div>
            <div class="secondcolumn">
                <div class="SmallImage">
                    <img src='<?php echo $this->getViewFileUrl("images/5f8819d07bb05d02aa218a4f_nuptse-evo-front-min.jpg"); ?>' alt="Demo">
                </div>
                <div class="TextBoxMiddle">
                    <h3>Szybkie zakładanie</h3>
                    <span class="P1">Nowa wersja Nuptse posiada ulepszony system regulacji. Dodatkowa dźwignia sprawia, że łatwo i szybko możemy wyregulować rozmiar raków. Regulacji można dokonać poprzez uniesienie dźwigni blokady ponad łącznik i dopasowanie długości do buta. Dzięki temu możliwe jest wykonanie operacji nawet w rękawicach. Raki Nuptse EVO można regulować w bardzo dużym zakresie (36-47) dzięki dwustopniowemu ustawieniu łącznika.</span>
                </div>
                <div class="SmallImage">
                    <img src='<?php echo $this->getViewFileUrl("images/5f8819d0a669ad60160a0633_nuptse-evo-back-min.jpg"); ?>' alt="Demo">
                </div>
            </div>
        </div>
    </div>
</div>