<div class="Raki-CT-Nuptse-EVO-Desktop">
    <div class="HeroCenter">
        <div class="HeroTxtWraperCenter">
            <div class="HeroTxtContent">
                <h4>CLIMBING TECHNOLOGY</h4>
                <div class="padding-16px"></div>
                <h1>RAKI NUPTSE EVO</h1>
                <div class="padding-16px"></div>
                <span class="Subheading">Włoska jakość doceniana wsród wymagających eksploratorów gór</span>
                <div class="padding-32px"></div>
            </div>
        </div>
        <div class="HeroImage"></div>
    </div>
</div>