<div class="Raki-CT-Nuptse-EVO-Desktop">
    <div class="TextBoxTop">
        <h2>Nowe rozwiązania, dopracowane w najmniejszym detalu</h2>
        <div class="padding-24px"></div>
        <span class="P1">Nuptse EVO to raki wykonane z najlepszej jakości hartowanej stali zapewniającej odpowiednią wytrzymałość i sztywność. 12 długich zębów opartych na ramowej konstrukcji zapewnia świetną przyczepność w lodzie oraz twardym i zmrożonym śniegu. </span>
        <div class="padding-24px"></div>
        <div class="padding-56px"></div>
        <div class="BigImage"></div>
    </div>
    <div class="TextBoxMiddle">
        <div class="padding-80px"></div>  
        <h3>Szybkie zakładanie</h3>
        <div class="padding-16px"></div>
        <span class="P1">Nowa wersja Nuptse posiada ulepszony system regulacji. Dodatkowa dźwignia sprawia, że łatwo i szybko możemy wyregulować rozmiar raków. Regulacji można dokonać poprzez uniesienie dźwigni blokady ponad łącznik i dopasowanie długości do buta. Dzięki temu możliwe jest wykonanie operacji nawet w rękawicach. Raki Nuptse EVO można regulować w bardzo dużym zakresie (36-47) dzięki dwustopniowemu ustawieniu łącznika.</span>
        <div class="padding-24px"></div>
        <div class="padding-56px"></div> 
    </div>
</div>